a=50
b=6
print(f"Addition is: {a} + {b}  = ", a+b)
print(f"Substraction is: {a} - {b}  = ", a-b)
print(f"Multiplication is: {a} * {b}  = ", a*b)
print(f"Division is: {a} / {b}  = ", a/b)
print(f"Modulus is: {a} % {b}  = ", a%b)
print(f"Exponentiation is: {a} ** {b}  = ", a**b)
print(f"Floor Division is: {a} % {b}  = ", a%b)
